# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _LBR
else:
    import _LBR

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _LBR.delete_SwigPyIterator

    def value(self):
        return _LBR.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _LBR.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _LBR.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _LBR.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _LBR.SwigPyIterator_equal(self, x)

    def copy(self):
        return _LBR.SwigPyIterator_copy(self)

    def next(self):
        return _LBR.SwigPyIterator_next(self)

    def __next__(self):
        return _LBR.SwigPyIterator___next__(self)

    def previous(self):
        return _LBR.SwigPyIterator_previous(self)

    def advance(self, n):
        return _LBR.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _LBR.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _LBR.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _LBR.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _LBR.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _LBR.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _LBR.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _LBR:
_LBR.SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _LBR.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _LBR.IntVector___nonzero__(self)

    def __bool__(self):
        return _LBR.IntVector___bool__(self)

    def __len__(self):
        return _LBR.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _LBR.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _LBR.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _LBR.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _LBR.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _LBR.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _LBR.IntVector___setitem__(self, *args)

    def pop(self):
        return _LBR.IntVector_pop(self)

    def append(self, x):
        return _LBR.IntVector_append(self, x)

    def empty(self):
        return _LBR.IntVector_empty(self)

    def size(self):
        return _LBR.IntVector_size(self)

    def swap(self, v):
        return _LBR.IntVector_swap(self, v)

    def begin(self):
        return _LBR.IntVector_begin(self)

    def end(self):
        return _LBR.IntVector_end(self)

    def rbegin(self):
        return _LBR.IntVector_rbegin(self)

    def rend(self):
        return _LBR.IntVector_rend(self)

    def clear(self):
        return _LBR.IntVector_clear(self)

    def get_allocator(self):
        return _LBR.IntVector_get_allocator(self)

    def pop_back(self):
        return _LBR.IntVector_pop_back(self)

    def erase(self, *args):
        return _LBR.IntVector_erase(self, *args)

    def __init__(self, *args):
        _LBR.IntVector_swiginit(self, _LBR.new_IntVector(*args))

    def push_back(self, x):
        return _LBR.IntVector_push_back(self, x)

    def front(self):
        return _LBR.IntVector_front(self)

    def back(self):
        return _LBR.IntVector_back(self)

    def assign(self, n, x):
        return _LBR.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _LBR.IntVector_resize(self, *args)

    def insert(self, *args):
        return _LBR.IntVector_insert(self, *args)

    def reserve(self, n):
        return _LBR.IntVector_reserve(self, n)

    def capacity(self):
        return _LBR.IntVector_capacity(self)
    __swig_destroy__ = _LBR.delete_IntVector

# Register IntVector in _LBR:
_LBR.IntVector_swigregister(IntVector)

class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _LBR.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _LBR.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _LBR.DoubleVector___bool__(self)

    def __len__(self):
        return _LBR.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _LBR.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _LBR.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _LBR.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _LBR.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _LBR.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _LBR.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _LBR.DoubleVector_pop(self)

    def append(self, x):
        return _LBR.DoubleVector_append(self, x)

    def empty(self):
        return _LBR.DoubleVector_empty(self)

    def size(self):
        return _LBR.DoubleVector_size(self)

    def swap(self, v):
        return _LBR.DoubleVector_swap(self, v)

    def begin(self):
        return _LBR.DoubleVector_begin(self)

    def end(self):
        return _LBR.DoubleVector_end(self)

    def rbegin(self):
        return _LBR.DoubleVector_rbegin(self)

    def rend(self):
        return _LBR.DoubleVector_rend(self)

    def clear(self):
        return _LBR.DoubleVector_clear(self)

    def get_allocator(self):
        return _LBR.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _LBR.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _LBR.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _LBR.DoubleVector_swiginit(self, _LBR.new_DoubleVector(*args))

    def push_back(self, x):
        return _LBR.DoubleVector_push_back(self, x)

    def front(self):
        return _LBR.DoubleVector_front(self)

    def back(self):
        return _LBR.DoubleVector_back(self)

    def assign(self, n, x):
        return _LBR.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _LBR.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _LBR.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _LBR.DoubleVector_reserve(self, n)

    def capacity(self):
        return _LBR.DoubleVector_capacity(self)
    __swig_destroy__ = _LBR.delete_DoubleVector

# Register DoubleVector in _LBR:
_LBR.DoubleVector_swigregister(DoubleVector)

class DoubleVector2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _LBR.DoubleVector2_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _LBR.DoubleVector2___nonzero__(self)

    def __bool__(self):
        return _LBR.DoubleVector2___bool__(self)

    def __len__(self):
        return _LBR.DoubleVector2___len__(self)

    def __getslice__(self, i, j):
        return _LBR.DoubleVector2___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _LBR.DoubleVector2___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _LBR.DoubleVector2___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _LBR.DoubleVector2___delitem__(self, *args)

    def __getitem__(self, *args):
        return _LBR.DoubleVector2___getitem__(self, *args)

    def __setitem__(self, *args):
        return _LBR.DoubleVector2___setitem__(self, *args)

    def pop(self):
        return _LBR.DoubleVector2_pop(self)

    def append(self, x):
        return _LBR.DoubleVector2_append(self, x)

    def empty(self):
        return _LBR.DoubleVector2_empty(self)

    def size(self):
        return _LBR.DoubleVector2_size(self)

    def swap(self, v):
        return _LBR.DoubleVector2_swap(self, v)

    def begin(self):
        return _LBR.DoubleVector2_begin(self)

    def end(self):
        return _LBR.DoubleVector2_end(self)

    def rbegin(self):
        return _LBR.DoubleVector2_rbegin(self)

    def rend(self):
        return _LBR.DoubleVector2_rend(self)

    def clear(self):
        return _LBR.DoubleVector2_clear(self)

    def get_allocator(self):
        return _LBR.DoubleVector2_get_allocator(self)

    def pop_back(self):
        return _LBR.DoubleVector2_pop_back(self)

    def erase(self, *args):
        return _LBR.DoubleVector2_erase(self, *args)

    def __init__(self, *args):
        _LBR.DoubleVector2_swiginit(self, _LBR.new_DoubleVector2(*args))

    def push_back(self, x):
        return _LBR.DoubleVector2_push_back(self, x)

    def front(self):
        return _LBR.DoubleVector2_front(self)

    def back(self):
        return _LBR.DoubleVector2_back(self)

    def assign(self, n, x):
        return _LBR.DoubleVector2_assign(self, n, x)

    def resize(self, *args):
        return _LBR.DoubleVector2_resize(self, *args)

    def insert(self, *args):
        return _LBR.DoubleVector2_insert(self, *args)

    def reserve(self, n):
        return _LBR.DoubleVector2_reserve(self, n)

    def capacity(self):
        return _LBR.DoubleVector2_capacity(self)
    __swig_destroy__ = _LBR.delete_DoubleVector2

# Register DoubleVector2 in _LBR:
_LBR.DoubleVector2_swigregister(DoubleVector2)

class DoubleVector3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _LBR.DoubleVector3_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _LBR.DoubleVector3___nonzero__(self)

    def __bool__(self):
        return _LBR.DoubleVector3___bool__(self)

    def __len__(self):
        return _LBR.DoubleVector3___len__(self)

    def __getslice__(self, i, j):
        return _LBR.DoubleVector3___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _LBR.DoubleVector3___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _LBR.DoubleVector3___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _LBR.DoubleVector3___delitem__(self, *args)

    def __getitem__(self, *args):
        return _LBR.DoubleVector3___getitem__(self, *args)

    def __setitem__(self, *args):
        return _LBR.DoubleVector3___setitem__(self, *args)

    def pop(self):
        return _LBR.DoubleVector3_pop(self)

    def append(self, x):
        return _LBR.DoubleVector3_append(self, x)

    def empty(self):
        return _LBR.DoubleVector3_empty(self)

    def size(self):
        return _LBR.DoubleVector3_size(self)

    def swap(self, v):
        return _LBR.DoubleVector3_swap(self, v)

    def begin(self):
        return _LBR.DoubleVector3_begin(self)

    def end(self):
        return _LBR.DoubleVector3_end(self)

    def rbegin(self):
        return _LBR.DoubleVector3_rbegin(self)

    def rend(self):
        return _LBR.DoubleVector3_rend(self)

    def clear(self):
        return _LBR.DoubleVector3_clear(self)

    def get_allocator(self):
        return _LBR.DoubleVector3_get_allocator(self)

    def pop_back(self):
        return _LBR.DoubleVector3_pop_back(self)

    def erase(self, *args):
        return _LBR.DoubleVector3_erase(self, *args)

    def __init__(self, *args):
        _LBR.DoubleVector3_swiginit(self, _LBR.new_DoubleVector3(*args))

    def push_back(self, x):
        return _LBR.DoubleVector3_push_back(self, x)

    def front(self):
        return _LBR.DoubleVector3_front(self)

    def back(self):
        return _LBR.DoubleVector3_back(self)

    def assign(self, n, x):
        return _LBR.DoubleVector3_assign(self, n, x)

    def resize(self, *args):
        return _LBR.DoubleVector3_resize(self, *args)

    def insert(self, *args):
        return _LBR.DoubleVector3_insert(self, *args)

    def reserve(self, n):
        return _LBR.DoubleVector3_reserve(self, n)

    def capacity(self):
        return _LBR.DoubleVector3_capacity(self)
    __swig_destroy__ = _LBR.delete_DoubleVector3

# Register DoubleVector3 in _LBR:
_LBR.DoubleVector3_swigregister(DoubleVector3)

class Model(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, X, dt, times):
        _LBR.Model_swiginit(self, _LBR.new_Model(X, dt, times))

    def CerebralBloodFlow(self):
        return _LBR.Model_CerebralBloodFlow(self)

    def LaminarBOLDResponse(self):
        return _LBR.Model_LaminarBOLDResponse(self)

    def get_CBF(self):
        return _LBR.Model_get_CBF(self)

    def get_LBR(self):
        return _LBR.Model_get_LBR(self)

    def get_LBR_pial(self):
        return _LBR.Model_get_LBR_pial(self)
    __swig_destroy__ = _LBR.delete_Model

# Register Model in _LBR:
_LBR.Model_swigregister(Model)



